/**
 * dsh-codehub — client bundle wrapper.
 *
 * WHY THIS FILE EXISTS
 * --------------------
 * DSH's browser-half contract is not "an ES module". The client module loader
 * serves a *closure factory* artifact: the file registers
 *
 *     window.__ModuleLoader__.load({
 *       id: '<package name>',
 *       factory(require) { /* module body *\/ return { apply, inject } },
 *     })
 *
 * and the factory is NOT executed at load time — it runs later, when the loader
 * materializes the module, with a `require` bound to the loader's module table.
 * Every browser half DSH ships follows that shape (verified against the emitted
 * lib/client.js of dsh-better-sidebar, dsh-context, dsh-drop-caret and
 * dsh-webview-clipboard: all open with `window.__ModuleLoader__.load({` and
 * close with the factory `});`).
 *
 * A plain `import`/`export` file cannot be that body: the factory has no ES
 * module scope. So the client half is compiled to CommonJS by tsdown
 * (see tsdown.config.ts) and this script wraps the result in the factory.
 *
 * Doing the wrapping here rather than in the bundler keeps the deferral honest:
 * the whole CommonJS chunk — including its `require(...)` calls to React and the
 * primitives package — sits *inside* `factory`, so nothing touches globals until
 * the loader actually materializes the module.
 *
 * Run by `pnpm run build`, after `tsc` (declarations) and `tsdown` (bundles).
 */

import { readFile, writeFile, rm } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

/** Repository root (this file lives in scripts/). */
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

/** The id the loader keys this bundle by. Must equal the package name. */
const CLIENT_ID = 'dsh-codehub'

/** tsdown's CommonJS chunk, wrapped into the final artifact below. */
const BUNDLE = path.join(ROOT, 'lib', 'client.cjs')

/** The artifact DSH serves for `exports['./client']`. */
const ARTIFACT = path.join(ROOT, 'lib', 'client.js')

/** Intro of the served artifact; matches the shipping browser halves. */
const INTRO = `// dsh-codehub — browser half, in the DSH client module loader format.
//
// GENERATED by scripts/wrap-client.mjs from lib/client.cjs. Do not edit this
// file: edit src/client/** and run \`pnpm run build\`.
//
// The module body is deferred into \`factory\`, which the loader calls when it
// materializes the module; \`require\` is bound to the loader's module table.

window.__ModuleLoader__.load({
  id: ${JSON.stringify(CLIENT_ID)},
  factory: function (require) {
    var module = { exports: {} };
    var exports = module.exports;
`

/** Outro closing the factory and recovering the module's exports. */
const OUTRO = `
    return module.exports;
  },
});
`

/**
 * Wrap the CommonJS chunk in the loader factory.
 *
 * Indentation is preserved rather than reflowed: the chunk is generated code,
 * and re-indenting several thousand lines would rewrite every template literal
 * and source map offset in it for no benefit.
 */
async function main() {
  let chunk
  try {
    chunk = await readFile(BUNDLE, 'utf8')
  } catch (error) {
    console.error(
      `wrap-client: cannot read ${BUNDLE}. Run \`pnpm run bundle\` first.\n` +
        `  ${error instanceof Error ? error.message : String(error)}`,
    )
    process.exitCode = 1
    return
  }

  await writeFile(ARTIFACT, INTRO + chunk + OUTRO, 'utf8')

  // The unwrapped chunk has no remaining consumer: package.json points at
  // lib/client.js, and leaving the intermediate would ship a second copy of the
  // browser half inside the package.
  try {
    await rm(BUNDLE, { force: true })
  } catch {
    // Non-fatal: a stale intermediate is untidy, not broken.
  }

  console.log(`wrap-client: wrote ${path.relative(ROOT, ARTIFACT)} (loader id ${CLIENT_ID})`)
}

await main()
