/**
 * dsh-codehub — client bundle wrapper.
 *
 * WHY THIS FILE EXISTS
 * --------------------
 * DSH's browser-half contract is not "an ES module". The client module loader
 * serves a *closure factory* artifact: the file registers
 *
 *     window.__ModuleLoader__.load({
 *       id: '<package name>',
 *       factory(require) { /* module body *\/ return { apply, inject } },
 *     })
 *
 * and the factory is NOT executed at load time — it runs later, when the loader
 * materializes the module, with a `require` bound to the loader's module table.
 * Every browser half DSH ships follows that shape (verified against the emitted
 * lib/client.js of dsh-better-sidebar, dsh-context, dsh-drop-caret and
 * dsh-webview-clipboard: all open with `window.__ModuleLoader__.load({` and
 * close with the factory `});`).
 *
 * A plain `import`/`export` file cannot be that body: the factory has no ES
 * module scope. So the client half is compiled to CommonJS by tsdown
 * (see tsdown.config.ts) and this script wraps the result in the factory.
 *
 * Doing the wrapping here rather than in the bundler keeps the deferral honest:
 * the whole CommonJS chunk — including its `require(...)` calls to React and the
 * primitives package — sits *inside* `factory`, so nothing touches globals until
 * the loader actually materializes the module.
 *
 * Run by `pnpm run build`, after `tsc` (declarations) and `tsdown` (bundles).
 */

import { readFile, writeFile, rm } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

/** Repository root (this file lives in scripts/). */
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

/** The id the loader keys this bundle by. Must equal the package name. */
const CLIENT_ID = 'dsh-codehub'

/** tsdown's CommonJS chunk, wrapped into the final artifact below. */
const BUNDLE = path.join(ROOT, 'lib', 'client.cjs')

/** The stylesheet tsdown emits next to the chunk; inlined, then removed. */
const STYLESHEET = path.join(ROOT, 'lib', 'client.css')

/** The artifact DSH serves for `exports['./client']`. */
const ARTIFACT = path.join(ROOT, 'lib', 'client.js')

/**
 * The CSS injection prologue.
 *
 * WHY THE STYLESHEET MUST BE INLINED
 * ----------------------------------
 * tsdown extracts `*.module.css` into `lib/client.css` and leaves the JS holding
 * only the scoped class-NAME map (`{ optionList: '_3O5m1a_optionList', … }`). With
 * the stylesheet left as a separate file, nothing ever loads it: DSH's client
 * module loader fetches the plugin's JS entry and nothing else, and a plugin has
 * no hook to register a second asset. Every class then resolves to a scope hash
 * with no rules behind it, so the whole panel renders UNSTYLED — dense, unspaced,
 * cramped — which is exactly how the placement chooser looked to the user.
 *
 * Shipping browser halves do not ship a sibling stylesheet at all (dsh-ssh's lib/
 * is client.js + index.js + types): they carry the CSS as a string inside the
 * bundle and inject one guarded `<style>` tag on materialization. This emits the
 * same thing, with the same `data-plugin-css` de-duplication marker, so a second
 * module materialization cannot stack duplicate sheets.
 *
 * `textContent` (never `innerHTML`) means the stylesheet text is never parsed as
 * HTML. The `typeof document` guard keeps the module importable where there is no
 * DOM (tests, SSR).
 *
 * @param cssText - the emitted stylesheet, verbatim.
 * @returns the prologue to place inside the factory, before the chunk.
 */
function cssInjection(cssText) {
  const tagId = `${CLIENT_ID}/lib/client.css`
  return `    //#region ${CLIENT_ID} stylesheet (inlined; see scripts/wrap-client.mjs)
    var __dshCssText = ${JSON.stringify(cssText)};
    var __dshCssTagId = ${JSON.stringify(tagId)};
    if (typeof document !== "undefined" && document.querySelector("style[data-plugin-css=" + JSON.stringify(__dshCssTagId) + "]") === null) {
      var __dshCssTag = document.createElement("style");
      __dshCssTag.dataset.plugin = ${JSON.stringify(CLIENT_ID)};
      __dshCssTag.dataset.pluginCss = __dshCssTagId;
      __dshCssTag.textContent = __dshCssText;
      document.head.appendChild(__dshCssTag);
    }
    //#endregion
`
}


/** Intro of the served artifact; matches the shipping browser halves. */
const INTRO = `// dsh-codehub — browser half, in the DSH client module loader format.
//
// GENERATED by scripts/wrap-client.mjs from lib/client.cjs. Do not edit this
// file: edit src/client/** and run \`pnpm run build\`.
//
// The module body is deferred into \`factory\`, which the loader calls when it
// materializes the module; \`require\` is bound to the loader's module table.

window.__ModuleLoader__.load({
  id: ${JSON.stringify(CLIENT_ID)},
  factory: function (require) {
    var module = { exports: {} };
    var exports = module.exports;
`

/** Outro closing the factory and recovering the module's exports. */
const OUTRO = `
    return module.exports;
  },
});
`

/**
 * Wrap the CommonJS chunk in the loader factory.
 *
 * Indentation is preserved rather than reflowed: the chunk is generated code,
 * and re-indenting several thousand lines would rewrite every template literal
 * and source map offset in it for no benefit.
 */
async function main() {
  let chunk
  try {
    chunk = await readFile(BUNDLE, 'utf8')
  } catch (error) {
    console.error(
      `wrap-client: cannot read ${BUNDLE}. Run \`pnpm run bundle\` first.\n` +
        `  ${error instanceof Error ? error.message : String(error)}`,
    )
    process.exitCode = 1
    return
  }

  // The stylesheet is optional: a build with no `*.module.css` import emits none.
  let cssText = ''
  try {
    cssText = await readFile(STYLESHEET, 'utf8')
  } catch {
    cssText = ''
  }

  const styles = cssText.trim().length > 0 ? cssInjection(cssText) : ''
  await writeFile(ARTIFACT, INTRO + styles + chunk + OUTRO, 'utf8')

  // Neither intermediate has a remaining consumer. In particular the standalone
  // stylesheet MUST go: it is now inlined above, and leaving it would ship a
  // second copy of the panel's CSS that nothing loads.
  for (const intermediate of [BUNDLE, ...(styles.length > 0 ? [STYLESHEET] : [])]) {
    try {
      await rm(intermediate, { force: true })
    } catch {
      // Non-fatal: a stale intermediate is untidy, not broken.
    }
  }

  const inlined = styles.length > 0 ? `, CSS inlined (${cssText.length}B)` : ', no CSS'
  console.log(
    `wrap-client: wrote ${path.relative(ROOT, ARTIFACT)} (loader id ${CLIENT_ID}${inlined})`,
  )
}

await main()
